# Generated by Django 5.1.1 on 2024-10-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('userPassword', models.CharField(max_length=40)),
                ('startDate', models.DateField()),
            ],
        ),
    ]
