# Generated by Django 5.1.1 on 2024-10-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
