# Generated by Django 5.1.1 on 2024-10-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPassword',
            field=models.CharField(max_length=128),
        ),
    ]
