# Generated by Django 5.1.1 on 2024-10-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0005_user_is_active_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('transactionTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('transactionTypeName', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('transactionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.transactiontypes')),
            ],
        ),
    ]
